spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/scaleph?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
      username: root
      password: 123456
    log:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/scaleph?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
      username: root
      password: 123456
  quartz:
    properties:
      org.quartz:
        dataSource:
          quartzDS:
            driver: com.mysql.cj.jdbc.Driver
            URL: jdbc:mysql://127.0.0.1:3306/scaleph?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
            user: root
            password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456

# log
logging:
  level:
    root: debug
    com.baomidou.mybatisplus.samples.quickstart: debug
    springfox.documentation: info
    org.springframework.boot.autoconfigure: info
    org.springframework.beans.factory: info
    org.springframework.context: info