version: "3.1"

services:

  mysql:
    image: bitnami/mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_DATABASE=breeze
    ports:
      - 3306:3306
    volumes:
      - ./mysql/my_custom.cnf:/opt/bitnami/mysql/conf/my_custom.cnf
      - ./mysql/init.d:/docker-entrypoint-initdb.d
    networks:
      - breeze

  redis:
    image: bitnami/redis:6.0
    container_name: redis
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=123456
    ports:
      - 6379:6379
    networks:
      - breeze

  jobmanager:
    image: flink:1.13.6-scala_2.12-java8
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
    ports:
      - 8081:8081
    command: jobmanager
    networks:
      - breeze
  taskmanager:
    image: flink:1.13.6-scala_2.12-java8
    depends_on:
      - jobmanager
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 8
    command: taskmanager
    scale: 1
    networks:
      - flink

networks:
  breeze:
    driver: bridge